grails.doc.authors = 'Jeff Brown, Burt Beckwith'
grails.doc.license = 'Apache License 2.0'
grails.doc.title = 'Cache Plugin'
//grails.doc.subtitle = ''
//grails.doc.copyright = ''
//grails.doc.footer = ''
